name: Test Checks
on: 
  pull_request:
    branches:
      - sparsify.alpha  # TODO: delete after merge
      - main
      - 'release/*'
  push:
    branches:
      - sparsify.alpha  # TODO: delete after merge
      - main
      - 'release/*'

jobs:
  test-setup:
    runs-on: ubuntu-latest
    outputs:
      base-diff: ${{ steps.base-check.outputs.output }}
      full-check: ${{ steps.full-check.outputs.output }}
      package: ${{ steps.package-check.outputs.output }}
      auto: ${{ steps.auto-check.outputs.output }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Checking if any code was changed"
        id: base-check
        run: >
          ((git diff --name-only origin/main HEAD | grep -E "[src|tests]/sparsify|setup.py")
          || (echo $GITHUB_REF | grep -E "refs/heads/[release/|main]"))
          && echo "::set-output name=output::1" || echo "::set-output name=output::0"
      - name: "Checking if sparsify.package was changed"
        id: package-check
        run: >
          ((git diff --name-only origin/main HEAD | grep -E "[src|tests]/sparsify/package|setup.py|.github")
          || (echo $GITHUB_REF | grep -E "refs/heads/[release/|main]"))
          && echo "::set-output name=output::1" || echo "::set-output name=output::0"
      - name: "Checking if sparsify.auto was changed"
        id: auto-check
        run: >
          ((git diff --name-only origin/main HEAD | grep -E "[src|tests]/sparsify/auto|setup.py|.github")
          || (echo $GITHUB_REF | grep -E "refs/heads/[release/|main]"))
          && echo "::set-output name=output::1" || echo "::set-output name=output::0"
  python-tests:
    runs-on: ubuntu-latest
    env:
      SPARSEZOO_TEST_MODE: "true"
    needs: test-setup
    if: ${{needs.test-setup.outputs.base-diff == 1}}
    steps:
      - uses: actions/checkout@v2
      - name: "⚙️ Install dependencies"
        run: pip3 install -e .[dev]
      - name: "🔬 Running base tests"
        run: make test
        env:
          SPARSEZOO_API_URL: https://staging-api.neuralmagic.com
    if: ${{needs.test-setup.outputs.package-diff == 1}}
    steps:
      - name: "🔬 Running package tests"
        run: make test TARGETS=package
        env:
          SPARSEZOO_API_URL: https://staging-api.neuralmagic.com
    if: ${{needs.test-setup.outputs.auto-diff == 1}}
    steps:
      - name: "🔬 Running auto tests"
        run: make test TARGETS=auto
        env:
          SPARSEZOO_API_URL: https://staging-api.neuralmagic.com

